### ISSUE TITLE
duplicate names in sbClockModels.xml 

### ISSUE THREAD

**Issue by rbouckaert** [genomescale/starbeast2#6]
The templates in sbClockModels.xml share a parameter called branchRates.c:$(n), which is a RealParameter in some places and an IntegerParameter in another. This leads to problems when loading a stored file from XML into BEAUti (throwing exceptions when re-loading XML).
To be safe, it is a good idea to make names unique.

**Comment by rbouckaert** [comment]
Related to this, sbClockModels.xml has multiple connector rules for clockRate.c:$(n), but each have different conditions. When reloading XML, each of these connector rules is triggered, resulting in disconnection of clockRate parameters from the log (as explained [here](https://groups.google.com/forum/#!topic/beast-users/Psqwvob7uK8)).

Replacing each rule by

			<connect srcID="clockRate.c:$(n)" targetID="tracelog" inputName="log" if="inlikelihood(clockRate.c:$(n)) and clockRate.c:$(n)/estimate=true"/>

fixes the problem, but making the clockRate parameter have a unique name would be even better.

**Comment by genomescale** [comment]
Should be fixed in version 0.13.2
